// lang.js - Übersetzungen für das Panorama-Projekt
const text = {
    de: {
        ausschnitt: "🌍 Ausschnitt:",
        schweiz: "Schweiz",
        europa: "Europa",
        welt: "Welt",
        kontur: "Panorama Kontur",
        gipfel: "Gipfel (Melodie):",
        taeler: "Täler (Bass):",
        abstand: "Linien-Abstand (Pixel):",
        tonart: "Tonart / Skala:",
        wellenform: "Wellenform (Klang):",
        lautstaerke: "Lautstärke:",
        dauer: "Dauer (Sekunden):",
        play: "🎵 Akkord abspielen"
    },
    fr: {
        ausschnitt: "🌍 Vue :",
        schweiz: "Suisse",
        europa: "Europe",
        welt: "Monde",
        kontur: "Contour du Panorama",
        gipfel: "Sommets (Médodie) :",
        taeler: "Vallées (Basses) :",
        abstand: "Distance des lignes (px) :",
        tonart: "Gamme / Échelle :",
        wellenform: "Forme d'onde :",
        lautstaerke: "Volume :",
        dauer: "Durée (secondes) :",
        play: "🎵 Jouer l'accord"
    },
    it: {
        ausschnitt: "🌍 Vista:",
        schweiz: "Svizzera",
        europa: "Europa",
        welt: "Mondo",
        kontur: "Contorno Panoramico",
        gipfel: "Cime (Melodia):",
        taeler: "Valli (Bassi):",
        abstand: "Distanza linee (pixel):",
        tonart: "Scala musicale:",
        wellenform: "Forma d'onda:",
        lautstaerke: "Volume:",
        dauer: "Durata (secondi):",
        play: "🎵 Suona accordo"
    },
    en: {
        ausschnitt: "🌍 View:",
        schweiz: "Switzerland",
        europa: "Europe",
        welt: "World",
        kontur: "Panorama Contour",
        gipfel: "Peaks (Melody):",
        taeler: "Valleys (Bass):",
        abstand: "Line Spacing (pixels):",
        tonart: "Scale / Mode:",
        wellenform: "Waveform (Timbre):",
        lautstaerke: "Volume:",
        dauer: "Duration (seconds):",
        play: "🎵 Play Chord"
    },
    uk: {
        ausschnitt: "🌍 Вигляд:",
        schweiz: "Швейцарія",
        europa: "Європа",
        welt: "Світ",
        kontur: "Контур панорами",
        gipfel: "Вершини (Мелодія):",
        taeler: "Долини (Бас):",
        abstand: "Відстань ліній (px):",
        tonart: "Лад / Гама:",
        wellenform: "Форма хвилі:",
        lautstaerke: "Гучність:",
        dauer: "Тривалість (сек):",
        play: "🎵 Зіграти акорд"
    },
    ru: {
        ausschnitt: "🌍 Вид:",
        schweiz: "Швейцария",
        europa: "Европа",
        welt: "Мир",
        kontur: "Контур панорамы",
        gipfel: "Пики (Мелодия):",
        taeler: "Долины (Бас):",
        abstand: "Расстояние линий (px):",
        tonart: "Лад / Гамма:",
        wellenform: "Форма волны:",
        lautstaerke: "Громкость:",
        dauer: "Длительность (сек):",
        play: "🎵 Сыграть аккорд"
    }
};