// lang.js - Übersetzungen für das Panorama-Projekt
const text = {
    de: {
        sprache: "Sprache:",
        ausschnitt: "🌍 Ausschnitt:",
        schweiz: "Schweiz",
        europa: "Europa",
        welt: "Welt",
        kontur: "Panorama Kontur",
        gipfel: "Gipfel (Melodie):",
        taeler: "Täler (Bass):",
        abstand: "Linien-Abstand (Pixel):",
        modus: "Wiedergabe-Modus:",
        mod_gleich: "Alle zusammen (Akkord)",
        mod_lr: "Von links nach rechts",
        mod_rl: "Von rechts nach links",
        tonart: "Tonart / Skala:",
        wellenform: "Wellenform (Klang):",
        lautstaerke: "Lautstärke:",
        dauer: "Dauer (Sekunden):",
        play: "🎵 Akkord abspielen",
        vergroessern: "Bild vergrößern"
    },
    fr: {
        sprache: "Langue :",
        ausschnitt: "🌍 Vue :",
        schweiz: "Suisse",
        europa: "Europe",
        welt: "Monde",
        kontur: "Contour du Panorama",
        gipfel: "Sommets (Médodie) :",
        taeler: "Vallées (Basses) :",
        abstand: "Distance des lignes (px) :",
        modus: "Mode de lecture :",
        mod_gleich: "Tous ensemble (Accord)",
        mod_lr: "De gauche à droite",
        mod_rl: "De droite à gauche",
        tonart: "Gamme / Échelle :",
        wellenform: "Forme d'onde :",
        lautstaerke: "Volume :",
        dauer: "Durée (secondes) :",
        play: "🎵 Jouer l'accord",
        vergroessern: "Agrandir l'image"
    },
    it: {
        sprache: "Lingua:",
        ausschnitt: "🌍 Vista:",
        schweiz: "Svizzera",
        europa: "Europa",
        welt: "Mondo",
        kontur: "Contorno Panoramico",
        gipfel: "Cime (Melodia):",
        taeler: "Valli (Bassi):",
        abstand: "Distanza linee (pixel):",
        modus: "Modalità di riproduzione:",
        mod_gleich: "Tutti insieme (Accordo)",
        mod_lr: "Da sinistra a destra",
        mod_rl: "Da destra a sinistra",
        tonart: "Scala musicale:",
        wellenform: "Forma d'onda:",
        lautstaerke: "Volume:",
        dauer: "Durata (secondi):",
        play: "🎵 Suona accordo",
        vergroessern: "Ingrandisci l'immagine"
    },
    en: {
        sprache: "Language:",
        ausschnitt: "🌍 View:",
        schweiz: "Switzerland",
        europa: "Europe",
        welt: "World",
        kontur: "Panorama Contour",
        gipfel: "Peaks (Melody):",
        taeler: "Valleys (Bass):",
        abstand: "Line Spacing (pixels):",
        modus: "Playback Mode:",
        mod_gleich: "All together (Chord)",
        mod_lr: "Left to Right",
        mod_rl: "Right to Left",
        tonart: "Scale / Mode:",
        wellenform: "Waveform (Timbre):",
        lautstaerke: "Volume:",
        dauer: "Duration (seconds):",
        play: "🎵 Play Chord",
        vergroessern: "Enlarge image"
    },
    uk: {
        sprache: "Мова:",
        ausschnitt: "🌍 Вигляд:",
        schweiz: "Швейцарія",
        europa: "Європа",
        welt: "Світ",
        kontur: "Контур панорами",
        gipfel: "Вершини (Мелодія):",
        taeler: "Долини (Бас):",
        abstand: "Відстань ліній (px):",
        modus: "Режим відтворення:",
        mod_gleich: "Всі разом (Акорд)",
        mod_lr: "Зліва направо",
        mod_rl: "Справа наліво",
        tonart: "Лад / Гама:",
        wellenform: "Форма хвилі:",
        lautstaerke: "Гучність:",
        dauer: "Тривалість (сек):",
        play: "🎵 Зіграти акорд",
        vergroessern: "Збільшити зображення"
    },
    ru: {
        sprache: "Язык:",
        ausschnitt: "🌍 Вид:",
        schweiz: "Швейцария",
        europa: "Европа",
        welt: "Мир",
        kontur: "Контур панорамы",
        gipfel: "Пики (Мелодия):",
        taeler: "Долины (Бас):",
        abstand: "Расстояние линий (px):",
        modus: "Режим воспроизведения:",
        mod_gleich: "Все вместе (Аккорд)",
        mod_lr: "Слева направо",
        mod_rl: "Справа налево",
        tonart: "Лад / Гамма:",
        wellenform: "Форма волны:",
        lautstaerke: "Громкость:",
        dauer: "Длительность (сек):",
        play: "🎵 Сыграть аккорд",
        vergroessern: "Увеличить изображение"
    }
};