// lang.js - Mehrsprachigkeit für den Panorama Synthesizer
const text = {
    de: {
        sprache: "Sprache:",
        ausschnitt: "🌍 Ausschnitt:",
        schweiz: "Schweiz",
        europa: "Europa",
        welt: "Welt",
        modus: "Modus",
        tonart: "Tonart",
        wellenform: "Patch",
        mod_gleich: "Akkord",
        mod_lr: "L -> R",
        mod_rl: "R -> L",
        scale_major: "Dur",
        scale_minor: "Moll",
        scale_lydian: "Lydisch",
        scale_dorian: "Dorisch",
        scale_pentatonic: "Pentatonik",
        scale_hirajoshi: "Hirajōshi",
        wave_sine: "Sinus",
        wave_triangle: "Dreieck",
        wave_sawtooth: "Sägezahn",
        wave_square: "Rechteck",
        wave_organ: "Orgel",
        wave_darkpad: "Dark Pad",
        wave_chime: "Glöckchen",
        gipfel: "Gipfel",
        taeler: "Täler",
        abstand: "Abstand",
        sensibilitaet: "Sensib.",
        oktaven: "Oktaven",
        range: "Scale",
        dauer: "Dauer",
        echo: "Echo",
        attack: "Attack",
        release: "Release",
        lautstaerke: "Vol",
        vergroessern: "Vergrößern",
        prompt_name_change: "Wie lautet dein (Spitz-)Name?",
        prompt_welcome: "Willkommen! Unter welchem (Spitz-)Namen sollen deine Presets gespeichert werden?",
        prompt_preset_name: "Hallo {name}, wie soll diese Klangeinstellung heissen?",
        alert_load_empty: "Bitte markiere ein Preset zum Laden.",
        alert_load_multi: "Zum Laden auf die Regler darf nur EIN Preset markiert sein.",
        alert_saved: "Erfolg! '{preset}' wurde gespeichert.",
        alert_net_error: "Netzwerkfehler beim Speichern.",
        alert_delete: "Möchtest du dieses Preset wirklich löschen?",
        alert_no_points: "Mit diesen Einstellungen wurden keine Punkte gefunden!",
        hint_play_current: "Aktuelles Panorama abspielen",
        hint_play_sel: "Ausgewählte Presets abspielen",
        hint_load_sel: "Markiertes Preset laden",
        hint_save: "Aktuelle Einstellung speichern"
    },
    fr: {
        sprache: "Langue:",
        ausschnitt: "🌍 Vue:",
        schweiz: "Suisse",
        europa: "Europe",
        welt: "Monde",
        modus: "Mode",
        tonart: "Gamme",
        wellenform: "Patch",
        mod_gleich: "Accord",
        mod_lr: "G -> D",
        mod_rl: "D -> G",
        scale_major: "Majeur",
        scale_minor: "Mineur",
        scale_lydian: "Lydien",
        scale_dorian: "Dorien",
        scale_pentatonic: "Pentatonique",
        scale_hirajoshi: "Hirajōshi",
        wave_sine: "Sinus",
        wave_triangle: "Triangle",
        wave_sawtooth: "Scie",
        wave_square: "Carré",
        wave_organ: "Orgue",
        wave_darkpad: "Dark Pad",
        wave_chime: "Carillon",
        gipfel: "Sommets",
        taeler: "Vallées",
        abstand: "Distance",
        sensibilitaet: "Sensib.",
        oktaven: "Octaves",
        range: "Échelle",
        dauer: "Durée",
        echo: "Écho",
        attack: "Attaque",
        release: "Relâche",
        lautstaerke: "Vol",
        vergroessern: "Agrandir",
        prompt_name_change: "Quel est ton pseudonyme ?",
        prompt_welcome: "Bienvenue ! Sous quel nom souhaitez-vous enregistrer vos préréglages ?",
        prompt_preset_name: "Bonjour {name}, quel est le nom de ce réglage ?",
        alert_load_empty: "Veuillez cocher un préréglage à charger.",
        alert_load_multi: "Un seul préréglage peut être sélectionné pour le chargement.",
        alert_saved: "Succès ! '{preset}' a été enregistré.",
        alert_net_error: "Erreur réseau lors de l'enregistrement.",
        alert_delete: "Voulez-vous vraiment supprimer ce préréglage ?",
        alert_no_points: "Aucun point trouvé avec ces paramètres !",
        hint_play_current: "Lire le panorama actuel",
        hint_play_sel: "Lire les préréglages sélectionnés",
        hint_load_sel: "Charger le préréglage sélectionné",
        hint_save: "Enregistrer le réglage actuel"
    },
    it: {
        sprache: "Lingua:",
        ausschnitt: "🌍 Vista:",
        schweiz: "Svizzera",
        europa: "Europa",
        welt: "Mondo",
        modus: "Modalità",
        tonart: "Scala",
        wellenform: "Patch",
        mod_gleich: "Accordo",
        mod_lr: "S -> D",
        mod_rl: "D -> S",
        scale_major: "Maggiore",
        scale_minor: "Minore",
        scale_lydian: "Lidio",
        scale_dorian: "Dorico",
        scale_pentatonic: "Pentatonica",
        scale_hirajoshi: "Hirajōshi",
        wave_sine: "Senso",
        wave_triangle: "Triangolo",
        wave_sawtooth: "Dente di sega",
        wave_square: "Onda quadra",
        wave_organ: "Organo",
        wave_darkpad: "Dark Pad",
        wave_chime: "Campanelli",
        gipfel: "Cime",
        taeler: "Valli",
        abstand: "Distanza",
        sensibilitaet: "Sensib.",
        oktaven: "Ottave",
        range: "Scala",
        dauer: "Durata",
        echo: "Eco",
        attack: "Attacco",
        release: "Rilascio",
        lautstaerke: "Vol",
        vergroessern: "Ingrandisci",
        prompt_name_change: "Qual è il tuo soprannome?",
        prompt_welcome: "Benvenuto! Con quale nome desideri salvare i tuoi preset?",
        prompt_preset_name: "Ciao {name}, come vuoi chiamare questa impostazione?",
        alert_load_empty: "Seleziona un preset da caricare.",
        alert_load_multi: "È consentito selezionare un solo preset per il caricamento.",
        alert_saved: "Successo! '{preset}' è stato salvato.",
        alert_net_error: "Errore di rete durante il salvataggio.",
        alert_delete: "Vuoi davvero eliminare questo preset?",
        alert_no_points: "Nessun punto trovato con queste impostazioni!",
        hint_play_current: "Riproduci panorama attuale",
        hint_play_sel: "Riproduci preset selezionati",
        hint_load_sel: "Carica preset selezionato",
        hint_save: "Salva impostazione corrente"
    },
    en: {
        sprache: "Language:",
        ausschnitt: "🌍 View:",
        schweiz: "Switzerland",
        europa: "Europe",
        welt: "World",
        modus: "Mode",
        tonart: "Scale Type",
        wellenform: "Patch",
        mod_gleich: "Chord",
        mod_lr: "L -> R",
        mod_rl: "R -> L",
        scale_major: "Major",
        scale_minor: "Minor",
        scale_lydian: "Lydian",
        scale_dorian: "Dorian",
        scale_pentatonic: "Pentatonic",
        scale_hirajoshi: "Hirajōshi",
        wave_sine: "Sine",
        wave_triangle: "Triangle",
        wave_sawtooth: "Sawtooth",
        wave_square: "Square",
        wave_organ: "Organ",
        wave_darkpad: "Dark Pad",
        wave_chime: "Chime",
        gipfel: "Peaks",
        taeler: "Valleys",
        abstand: "Spacing",
        sensibilitaet: "Sensib.",
        oktaven: "Octaves",
        range: "Scale",
        dauer: "Duration",
        echo: "Echo",
        attack: "Attack",
        release: "Release",
        lautstaerke: "Vol",
        vergroessern: "Enlarge",
        prompt_name_change: "What is your nickname?",
        prompt_welcome: "Welcome! Under what name should your presets be saved?",
        prompt_preset_name: "Hello {name}, what should this sound setting be called?",
        alert_load_empty: "Please check a preset to load.",
        alert_load_multi: "Only ONE preset can be checked for loading.",
        alert_saved: "Success! '{preset}' was saved.",
        alert_net_error: "Network error while saving.",
        alert_delete: "Do you really want to delete this preset?",
        alert_no_points: "No points found with these settings!",
        hint_play_current: "Play current panorama",
        hint_play_sel: "Play selected presets",
        hint_load_sel: "Load selected preset",
        hint_save: "Save current setting"
    },
    uk: {
        sprache: "Мова:",
        ausschnitt: "🌍 Регіон:",
        schweiz: "Швейцарія",
        europa: "Європа",
        welt: "Світ",
        modus: "Режим",
        tonart: "Лад",
        wellenform: "Патч",
        mod_gleich: "Акорд",
        mod_lr: "Л -> П",
        mod_rl: "П -> Л",
        scale_major: "Мажор",
        scale_minor: "Мінор",
        scale_lydian: "Лідійський",
        scale_dorian: "Дорійський",
        scale_pentatonic: "Пентатоніка",
        scale_hirajoshi: "Хірадзьосі",
        wave_sine: "Синус",
        wave_triangle: "Трикутник",
        wave_sawtooth: "Пила",
        wave_square: "Прямокутник",
        wave_organ: "Орган",
        wave_darkpad: "Dark Pad",
        wave_chime: "Дзвіночки",
        gipfel: "Вершини",
        taeler: "Долини",
        abstand: "Відступ",
        sensibilitaet: "Чутлив.",
        oktaven: "Октави",
        range: "Шкала",
        dauer: "Тривалу.",
        echo: "Ехо",
        attack: "Атака",
        release: "Затухан.",
        lautstaerke: "Гучн.",
        vergroessern: "Збільшити",
        prompt_name_change: "Як ваше ім'я / псевдонім?",
        prompt_welcome: "Ласкаво просимо! Під яким ім'ям зберегти ваші налаштування?",
        prompt_preset_name: "Вітаю, {name}, як назвати цей пресет?",
        alert_load_empty: "Будь ласка, виберіть пресет для завантаження.",
        alert_load_multi: "Для завантаження можна вибрати лише ОДИН пресет.",
        alert_saved: "Успіх! '{preset}' збережено.",
        alert_net_error: "Посилка мережі під час збереження.",
        alert_delete: "Ви дійсно хочете видалити цей пресет?",
        alert_no_points: "З цими налаштуваннями точок не знайдено!",
        hint_play_current: "Відтворити поточну панораму",
        hint_play_sel: "Відтворити вибрані пресети",
        hint_load_sel: "Завантажити вибраний пресет",
        hint_save: "Зберегти поточні налаштування"
    },
    ru: {
        sprache: "Язык:",
        ausschnitt: "🌍 Вид:",
        schweiz: "Швейцария",
        europa: "Европа",
        welt: "Мир",
        modus: "Режим",
        tonart: "Лад",
        wellenform: "Патч",
        mod_gleich: "Аккорд",
        mod_lr: "Л -> П",
        mod_rl: "П -> Л",
        scale_major: "Мажор",
        scale_minor: "Минор",
        scale_lydian: "Лидийский",
        scale_dorian: "Дорийский",
        scale_pentatonic: "Пентатоника",
        scale_hirajoshi: "Хирадзёси",
        wave_sine: "Синус",
        wave_triangle: "Треугольник",
        wave_sawtooth: "Пила",
        wave_square: "Квадрат",
        wave_organ: "Орган",
        wave_darkpad: "Dark Pad",
        wave_chime: "Колокольчики",
        gipfel: "Пики",
        taeler: "Долины",
        abstand: "Шаг",
        sensibilitaet: "Чувствит.",
        oktaven: "Октавы",
        range: "Шкала",
        dauer: "Длительн.",
        echo: "Эхо",
        attack: "Атака",
        release: "Релиз",
        lautstaerke: "Громк.",
        vergroessern: "Увеличить",
        prompt_name_change: "Как ваше имя / псевдоним?",
        prompt_welcome: "Добро пожаловать! Под каким именем сохранить ваши пресеты?",
        prompt_preset_name: "Привет, {name}, как назвать эту настройку?",
        alert_load_empty: "Пожалуйста, выберите пресет для загрузки.",
        alert_load_multi: "Для загрузки можно выбрать только ОДИН пресет.",
        alert_saved: "Успех! '{preset}' сохранен.",
        alert_net_error: "Ошибка сети при сохранении.",
        alert_delete: "Вы действительно хотите удалить этот пресет?",
        alert_no_points: "С этими настройками точек не найдено!",
        hint_play_current: "Воспроизвести текущую панораму",
        hint_play_sel: "Воспроизвести выбранные пресеты",
        hint_load_sel: "Загрузить выбранный пресет",
        hint_save: "Сохранить текущую настройку"
    }
};